package graduationProject.graduation_judge.domain.Graduation.repository;

import graduationProject.graduation_judge.DAO.CoreLectureRequirement;
import graduationProject.graduation_judge.DAO.identifier.CoreLectureRequirementPK;
import graduationProject.graduation_judge.domain.Graduation.repository.QueryDsl.CoreLectureReqCustom;
import org.springframework.data.jpa.repository.JpaRepository;

public interface CoreLectureRequirementRepository extends JpaRepository<CoreLectureRequirement, CoreLectureRequirementPK>, CoreLectureReqCustom {
}